# Generated by Django 4.1.3 on 2022-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Name', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('password', models.CharField(db_column='Password', max_length=20)),
                ('phone', models.IntegerField(db_column='Phone')),
                ('address', models.CharField(db_column='Address', max_length=40)),
                ('zipcode', models.IntegerField(db_column='Zipcode')),
                ('state', models.CharField(db_column='State', max_length=30)),
            ],
        ),
    ]
