# Generated by Django 4.1.3 on 2022-12-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('car_id', models.AutoField(db_column='Car_id', primary_key=True, serialize=False)),
                ('brand', models.CharField(db_column='Brand', max_length=20)),
                ('model', models.CharField(db_column='Model', max_length=20)),
                ('series', models.CharField(db_column='Series', max_length=20)),
                ('year', models.IntegerField(db_column='Year')),
                ('color', models.CharField(db_column='Color', max_length=20)),
                ('photo', models.ImageField(blank=True, db_column='photo', max_length=200, null=True, upload_to='photo')),
                ('insurance_till', models.DateField(db_column='Insurance_Till')),
                ('kms_driven', models.IntegerField(db_column='Kms_Driven')),
                ('expected_prize', models.IntegerField(db_column='Expected_Prize')),
                ('fuel_type', models.CharField(db_column='Fuel_Type', max_length=20)),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='user.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryDetails',
            fields=[
                ('e_id', models.AutoField(db_column='E_id', primary_key=True, serialize=False)),
                ('message', models.IntegerField(db_column='Message', default=0)),
                ('car_id', models.ForeignKey(db_column='Car_id', on_delete=django.db.models.deletion.CASCADE, to='user.cardetails')),
                ('interested_user_id', models.ForeignKey(db_column='Int_User_id', on_delete=django.db.models.deletion.CASCADE, to='user.userdetails')),
            ],
        ),
    ]
