# Generated by Django 4.1.3 on 2022-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cardetails_enquirydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(blank=True, db_column='photo', max_length=200, null=True, upload_to='user/photo'),
        ),
    ]
