# Generated by Django 4.1.3 on 2022-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_cardetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photos',
            field=models.ImageField(blank=True, db_column='photos', max_length=200, null=True, upload_to='photo'),
        ),
    ]
