# Generated by Django 4.1.3 on 2022-12-10 14:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cardetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(blank=True, db_column='photos', max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='photos'),
        ),
    ]
