# Generated by Django 4.1.3 on 2022-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cardetails_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='photos',
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
